### ISSUE TITLE
Not running in python3.4

### ISSUE THREAD

**Issue by ekartsonakis** [JohannesEbke/aws_list_all#32]
Hi, Very nice work!

I tried aws_list_all in python 2.7 and it worked as expected without any problems. However when I moved to another system with a virtualenv using python 3.4, I get errors like the following. 

```(aws) [user@sbx scripts]$ aws-list-all query
--------------------------------------------------------------------------------
WARNING!
Your system limits the number of open files and network connections to 4096.
This may lead to failures during querying.
Please increase the hard limit of open files to at least 6000.
The configuration for hard limits is often found in /etc/security/limits.conf
--------------------------------------------------------------------------------

Increasing the open connection limit "nofile" from 3072 to 4096.

Building set of queries to execute...
Traceback (most recent call last):
  File "/home/user/scripts/aws/lib/python3.4/site-packages/app_json_file_cache/function_cache.py", line 17, in f
    return self.get(key)
  File "/home/user/scripts/aws/lib/python3.4/site-packages/app_json_file_cache/data_cache.py", line 27, in get
    return self._data[key_string]['data']
KeyError: '{"args": [], "kwargs": {}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/scripts/aws/bin/aws-list-all", line 10, in <module>
    sys.exit(main())
  File "/home/user/scripts/aws/lib/python3.4/site-packages/aws_list_all/__main__.py", line 142, in main
    do_query(services, args.region, args.operation, verbose=args.verbose or 0, parallel=args.parallel)
  File "/home/user/scripts/aws/lib/python3.4/site-packages/aws_list_all/query.py", line 203, in do_query
    for region in get_regions_for_service(service, selected_regions):
  File "/home/user/scripts/aws/lib/python3.4/site-packages/aws_list_all/introspection.py", line 373, in get_regions_for_service
    regions = set(get_service_regions().get(requested_service, []))
  File "/home/user/scripts/aws/lib/python3.4/site-packages/app_json_file_cache/function_cache.py", line 20, in f
    return self._cheap_default_func(*args, **kwargs)
  File "/home/user/scripts/aws/lib/python3.4/site-packages/aws_list_all/introspection.py", line 355, in packaged_service_regions
    return load(resource_stream(__package__, 'service_regions.json'))['data']
  File "/usr/lib64/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

I will try troubleshoot later and come back in case I find something.

**Comment by caublet** [comment]
Same here with version 3.5

**Comment by gliptak** [comment]
Both Python ```3.4``` and ```3.5``` are EOL https://www.python.org/downloads/

https://github.com/JohannesEbke/aws_list_all/issues/40

**Comment by JohannesEbke** [comment]
I should probably add a check so that the error message improves.
