### ISSUE TITLE
ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by emeyedeejay** [JohannesEbke/aws_list_all#35]
Newbie alert! Just getting into both AWS and Python.

Trying to run aws-list-all and I get the following error message.
Python 3.8.2
Windows 10.

```
(aws-list-all) C:\Program Files (x86)\Python38-32\aws-list-all\Scripts>aws-list-all query --region eu-west-1 --service ec2
Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\aws-list-all\Scripts\aws-list-all.exe\__main__.py", line 4, in <module>
  File "c:\program files (x86)\python38-32\aws-list-all\lib\site-packages\aws_list_all\__main__.py", line 5, in <module>
    from resource import getrlimit, setrlimit, RLIMIT_NOFILE
ModuleNotFoundError: No module named 'resource'
```

**Comment by DamienSynthesis** [comment]
Are you running the script on Windows, because resource is a Unix specific library for Python. https://docs.python.org/3/library/resource.html. Try running in Linux or under WSL.

**Comment by FeiYoungP2P** [comment]
What if the version of my system is windows8.1? It seems to be unable to install WSL. What should I do?
